// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthErrors, GetHealthResponses, ListMachinesData, ListMachinesErrors, ListMachinesResponses, ListNetworksData, ListNetworksErrors, ListNetworksResponses, ListPackagesData, ListPackagesErrors, ListPackagesResponses, ListVolumesData, ListVolumesErrors, ListVolumesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({ url: '/api/health', ...options });

export const listMachines = <ThrowOnError extends boolean = false>(options?: Options<ListMachinesData, ThrowOnError>): RequestResult<ListMachinesResponses, ListMachinesErrors, ThrowOnError> => (options?.client ?? client).get<ListMachinesResponses, ListMachinesErrors, ThrowOnError>({ url: '/api/v1/machines', ...options });

export const listPackages = <ThrowOnError extends boolean = false>(options?: Options<ListPackagesData, ThrowOnError>): RequestResult<ListPackagesResponses, ListPackagesErrors, ThrowOnError> => (options?.client ?? client).get<ListPackagesResponses, ListPackagesErrors, ThrowOnError>({ url: '/api/v1/packages', ...options });

export const listNetworks = <ThrowOnError extends boolean = false>(options?: Options<ListNetworksData, ThrowOnError>): RequestResult<ListNetworksResponses, ListNetworksErrors, ThrowOnError> => (options?.client ?? client).get<ListNetworksResponses, ListNetworksErrors, ThrowOnError>({ url: '/api/v1/networks', ...options });

export const listVolumes = <ThrowOnError extends boolean = false>(options?: Options<ListVolumesData, ThrowOnError>): RequestResult<ListVolumesResponses, ListVolumesErrors, ThrowOnError> => (options?.client ?? client).get<ListVolumesResponses, ListVolumesErrors, ThrowOnError>({ url: '/api/v1/volumes', ...options });
