// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Health = {
    status: 'ok';
    version: string;
    kraftVersion: string;
};

export type Error = {
    code: string;
    message: string;
};

export type Machine = {
    id?: string;
    name: string;
    kernel?: string;
    args?: string;
    created?: string;
    status: string;
    memory?: string;
    ports?: string;
    ip?: string;
    pid?: string;
    platform: string;
    architecture: string;
};

export type Package = {
    name: string;
    version: string;
    type: string;
    format?: string;
    platform?: string;
    architecture?: string;
    size?: string;
    created?: string;
    updated?: string;
    pulled?: string;
    description?: string;
    origin?: string;
    index?: string;
    manifest?: string;
};

export type Network = {
    machineId?: string;
    name: string;
    network?: string;
    driver: string;
    status: string;
};

export type Volume = {
    id?: string;
    name: string;
    driver: string;
    status: string;
    source?: string;
    destination?: string;
};

export type AllMachines = boolean;

export type Platform = string;

export type Architecture = string;

export type LongOutput = boolean;

export type Limit = number;

export type PackageKind = 'all' | 'app' | 'lib' | 'core';

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthErrors = {
    /**
     * The configured Kraft CLI is unavailable or incompatible.
     */
    503: Error;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
    /**
     * KraftUI and its configured Kraft CLI are ready.
     */
    200: Health;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListMachinesData = {
    body?: never;
    path?: never;
    query?: {
        all?: boolean;
        platform?: string;
        architecture?: string;
        long?: boolean;
    };
    url: '/api/v1/machines';
};

export type ListMachinesErrors = {
    /**
     * The request did not match the documented query parameters.
     */
    400: Error;
    /**
     * The Kraft CLI failed or produced an unsupported response.
     */
    502: Error;
};

export type ListMachinesError = ListMachinesErrors[keyof ListMachinesErrors];

export type ListMachinesResponses = {
    /**
     * Local machines.
     */
    200: Array<Machine>;
};

export type ListMachinesResponse = ListMachinesResponses[keyof ListMachinesResponses];

export type ListPackagesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        kind?: 'all' | 'app' | 'lib' | 'core';
        platform?: string;
        architecture?: string;
    };
    url: '/api/v1/packages';
};

export type ListPackagesErrors = {
    /**
     * The request did not match the documented query parameters.
     */
    400: Error;
    /**
     * The Kraft CLI failed or produced an unsupported response.
     */
    502: Error;
};

export type ListPackagesError = ListPackagesErrors[keyof ListPackagesErrors];

export type ListPackagesResponses = {
    /**
     * Locally available packages.
     */
    200: Array<Package>;
};

export type ListPackagesResponse = ListPackagesResponses[keyof ListPackagesResponses];

export type ListNetworksData = {
    body?: never;
    path?: never;
    query?: {
        long?: boolean;
    };
    url: '/api/v1/networks';
};

export type ListNetworksErrors = {
    /**
     * The request did not match the documented query parameters.
     */
    400: Error;
    /**
     * The Kraft CLI failed or produced an unsupported response.
     */
    502: Error;
};

export type ListNetworksError = ListNetworksErrors[keyof ListNetworksErrors];

export type ListNetworksResponses = {
    /**
     * Local machine networks.
     */
    200: Array<Network>;
};

export type ListNetworksResponse = ListNetworksResponses[keyof ListNetworksResponses];

export type ListVolumesData = {
    body?: never;
    path?: never;
    query?: {
        long?: boolean;
    };
    url: '/api/v1/volumes';
};

export type ListVolumesErrors = {
    /**
     * The request did not match the documented query parameters.
     */
    400: Error;
    /**
     * The Kraft CLI failed or produced an unsupported response.
     */
    502: Error;
};

export type ListVolumesError = ListVolumesErrors[keyof ListVolumesErrors];

export type ListVolumesResponses = {
    /**
     * Local machine volumes.
     */
    200: Array<Volume>;
};

export type ListVolumesResponse = ListVolumesResponses[keyof ListVolumesResponses];
