//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for PackageKind.
const (
	PackageKindAll  PackageKind = "all"
	PackageKindApp  PackageKind = "app"
	PackageKindCore PackageKind = "core"
	PackageKindLib  PackageKind = "lib"
)

// Valid indicates whether the value is a known member of the PackageKind enum.
func (e PackageKind) Valid() bool {
	switch e {
	case PackageKindAll:
		return true
	case PackageKindApp:
		return true
	case PackageKindCore:
		return true
	case PackageKindLib:
		return true
	default:
		return false
	}
}

// Defines values for ListPackagesParamsKind.
const (
	ListPackagesParamsKindAll  ListPackagesParamsKind = "all"
	ListPackagesParamsKindApp  ListPackagesParamsKind = "app"
	ListPackagesParamsKindCore ListPackagesParamsKind = "core"
	ListPackagesParamsKindLib  ListPackagesParamsKind = "lib"
)

// Valid indicates whether the value is a known member of the ListPackagesParamsKind enum.
func (e ListPackagesParamsKind) Valid() bool {
	switch e {
	case ListPackagesParamsKindAll:
		return true
	case ListPackagesParamsKindApp:
		return true
	case ListPackagesParamsKindCore:
		return true
	case ListPackagesParamsKindLib:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	KraftVersion string       `json:"kraftVersion"`
	Status       HealthStatus `json:"status"`
	Version      string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Machine defines model for Machine.
type Machine struct {
	Architecture string  `json:"architecture"`
	Args         *string `json:"args,omitempty"`
	Created      *string `json:"created,omitempty"`
	Id           *string `json:"id,omitempty"`
	Ip           *string `json:"ip,omitempty"`
	Kernel       *string `json:"kernel,omitempty"`
	Memory       *string `json:"memory,omitempty"`
	Name         string  `json:"name"`
	Pid          *string `json:"pid,omitempty"`
	Platform     string  `json:"platform"`
	Ports        *string `json:"ports,omitempty"`
	Status       string  `json:"status"`
}

// Network defines model for Network.
type Network struct {
	Driver    string  `json:"driver"`
	MachineId *string `json:"machineId,omitempty"`
	Name      string  `json:"name"`
	Network   *string `json:"network,omitempty"`
	Status    string  `json:"status"`
}

// Package defines model for Package.
type Package struct {
	Architecture *string `json:"architecture,omitempty"`
	Created      *string `json:"created,omitempty"`
	Description  *string `json:"description,omitempty"`
	Format       *string `json:"format,omitempty"`
	Index        *string `json:"index,omitempty"`
	Manifest     *string `json:"manifest,omitempty"`
	Name         string  `json:"name"`
	Origin       *string `json:"origin,omitempty"`
	Platform     *string `json:"platform,omitempty"`
	Pulled       *string `json:"pulled,omitempty"`
	Size         *string `json:"size,omitempty"`
	Type         string  `json:"type"`
	Updated      *string `json:"updated,omitempty"`
	Version      string  `json:"version"`
}

// Volume defines model for Volume.
type Volume struct {
	Destination *string `json:"destination,omitempty"`
	Driver      string  `json:"driver"`
	Id          *string `json:"id,omitempty"`
	Name        string  `json:"name"`
	Source      *string `json:"source,omitempty"`
	Status      string  `json:"status"`
}

// AllMachines defines model for AllMachines.
type AllMachines = bool

// Architecture defines model for Architecture.
type Architecture = string

// Limit defines model for Limit.
type Limit = int

// LongOutput defines model for LongOutput.
type LongOutput = bool

// PackageKind defines model for PackageKind.
type PackageKind string

// Platform defines model for Platform.
type Platform = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// KraftFailure defines model for KraftFailure.
type KraftFailure = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// ListMachinesParams defines parameters for ListMachines.
type ListMachinesParams struct {
	All          *AllMachines  `form:"all,omitempty" json:"all,omitempty"`
	Platform     *Platform     `form:"platform,omitempty" json:"platform,omitempty"`
	Architecture *Architecture `form:"architecture,omitempty" json:"architecture,omitempty"`
	Long         *LongOutput   `form:"long,omitempty" json:"long,omitempty"`
}

// ListNetworksParams defines parameters for ListNetworks.
type ListNetworksParams struct {
	Long *LongOutput `form:"long,omitempty" json:"long,omitempty"`
}

// ListPackagesParams defines parameters for ListPackages.
type ListPackagesParams struct {
	Limit        *Limit                  `form:"limit,omitempty" json:"limit,omitempty"`
	Kind         *ListPackagesParamsKind `form:"kind,omitempty" json:"kind,omitempty"`
	Platform     *Platform               `form:"platform,omitempty" json:"platform,omitempty"`
	Architecture *Architecture           `form:"architecture,omitempty" json:"architecture,omitempty"`
}

// ListPackagesParamsKind defines parameters for ListPackages.
type ListPackagesParamsKind string

// ListVolumesParams defines parameters for ListVolumes.
type ListVolumesParams struct {
	Long *LongOutput `form:"long,omitempty" json:"long,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/machines)
	ListMachines(w http.ResponseWriter, r *http.Request, params ListMachinesParams)

	// (GET /api/v1/networks)
	ListNetworks(w http.ResponseWriter, r *http.Request, params ListNetworksParams)

	// (GET /api/v1/packages)
	ListPackages(w http.ResponseWriter, r *http.Request, params ListPackagesParams)

	// (GET /api/v1/volumes)
	ListVolumes(w http.ResponseWriter, r *http.Request, params ListVolumesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMachines operation middleware
func (siw *ServerInterfaceWrapper) ListMachines(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMachinesParams

	// ------------- Optional query parameter "all" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "all", r.URL.Query(), &params.All, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "all"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "all", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "platform", r.URL.Query(), &params.Platform, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "platform"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "architecture" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "architecture", r.URL.Query(), &params.Architecture, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "architecture"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "architecture", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "long" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "long", r.URL.Query(), &params.Long, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "long"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "long", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMachines(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNetworks operation middleware
func (siw *ServerInterfaceWrapper) ListNetworks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNetworksParams

	// ------------- Optional query parameter "long" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "long", r.URL.Query(), &params.Long, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "long"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "long", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNetworks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPackages operation middleware
func (siw *ServerInterfaceWrapper) ListPackages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPackagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "platform", r.URL.Query(), &params.Platform, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "platform"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "architecture" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "architecture", r.URL.Query(), &params.Architecture, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "architecture"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "architecture", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPackages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVolumes operation middleware
func (siw *ServerInterfaceWrapper) ListVolumes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVolumesParams

	// ------------- Optional query parameter "long" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "long", r.URL.Query(), &params.Long, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "long"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "long", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVolumes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/machines", wrapper.ListMachines)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/packages", wrapper.ListPackages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/networks", wrapper.ListNetworks)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/volumes", wrapper.ListVolumes)

	return m
}

type BadRequestJSONResponse Error

type KraftFailureJSONResponse Error

type ServiceUnavailableJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListMachinesRequestObject struct {
	Params ListMachinesParams
}

type ListMachinesResponseObject interface {
	VisitListMachinesResponse(w http.ResponseWriter) error
}

type ListMachines200JSONResponse []Machine

func (response ListMachines200JSONResponse) VisitListMachinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMachines400JSONResponse struct{ BadRequestJSONResponse }

func (response ListMachines400JSONResponse) VisitListMachinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListMachines502JSONResponse struct{ KraftFailureJSONResponse }

func (response ListMachines502JSONResponse) VisitListMachinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ListNetworksRequestObject struct {
	Params ListNetworksParams
}

type ListNetworksResponseObject interface {
	VisitListNetworksResponse(w http.ResponseWriter) error
}

type ListNetworks200JSONResponse []Network

func (response ListNetworks200JSONResponse) VisitListNetworksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNetworks400JSONResponse struct{ BadRequestJSONResponse }

func (response ListNetworks400JSONResponse) VisitListNetworksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListNetworks502JSONResponse struct{ KraftFailureJSONResponse }

func (response ListNetworks502JSONResponse) VisitListNetworksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ListPackagesRequestObject struct {
	Params ListPackagesParams
}

type ListPackagesResponseObject interface {
	VisitListPackagesResponse(w http.ResponseWriter) error
}

type ListPackages200JSONResponse []Package

func (response ListPackages200JSONResponse) VisitListPackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPackages400JSONResponse struct{ BadRequestJSONResponse }

func (response ListPackages400JSONResponse) VisitListPackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListPackages502JSONResponse struct{ KraftFailureJSONResponse }

func (response ListPackages502JSONResponse) VisitListPackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ListVolumesRequestObject struct {
	Params ListVolumesParams
}

type ListVolumesResponseObject interface {
	VisitListVolumesResponse(w http.ResponseWriter) error
}

type ListVolumes200JSONResponse []Volume

func (response ListVolumes200JSONResponse) VisitListVolumesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVolumes400JSONResponse struct{ BadRequestJSONResponse }

func (response ListVolumes400JSONResponse) VisitListVolumesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListVolumes502JSONResponse struct{ KraftFailureJSONResponse }

func (response ListVolumes502JSONResponse) VisitListVolumesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)

	// (GET /api/v1/machines)
	ListMachines(ctx context.Context, request ListMachinesRequestObject) (ListMachinesResponseObject, error)

	// (GET /api/v1/networks)
	ListNetworks(ctx context.Context, request ListNetworksRequestObject) (ListNetworksResponseObject, error)

	// (GET /api/v1/packages)
	ListPackages(ctx context.Context, request ListPackagesRequestObject) (ListPackagesResponseObject, error)

	// (GET /api/v1/volumes)
	ListVolumes(ctx context.Context, request ListVolumesRequestObject) (ListVolumesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMachines operation middleware
func (sh *strictHandler) ListMachines(w http.ResponseWriter, r *http.Request, params ListMachinesParams) {
	var request ListMachinesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMachines(ctx, request.(ListMachinesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMachines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMachinesResponseObject); ok {
		if err := validResponse.VisitListMachinesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNetworks operation middleware
func (sh *strictHandler) ListNetworks(w http.ResponseWriter, r *http.Request, params ListNetworksParams) {
	var request ListNetworksRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNetworks(ctx, request.(ListNetworksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNetworks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNetworksResponseObject); ok {
		if err := validResponse.VisitListNetworksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPackages operation middleware
func (sh *strictHandler) ListPackages(w http.ResponseWriter, r *http.Request, params ListPackagesParams) {
	var request ListPackagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPackages(ctx, request.(ListPackagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPackages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPackagesResponseObject); ok {
		if err := validResponse.VisitListPackagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVolumes operation middleware
func (sh *strictHandler) ListVolumes(w http.ResponseWriter, r *http.Request, params ListVolumesParams) {
	var request ListVolumesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVolumes(ctx, request.(ListVolumesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVolumes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVolumesResponseObject); ok {
		if err := validResponse.VisitListVolumesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFhNc9s2EP0rGLRH1pKT5sKb2+mHJ27qaRtfMj6siBWFCATgBahGzfC/dwCSImWDstQkSm8msNqP994C",
	"C3/khams0ai94/lHboGgQo8Uv66U+g2KldQYP6XmOX+okbY84xoq5DkHpXjGXbHCCoKNwCXUyvPcU40Z",
	"91sbrBbGKATNmybjV1SspMfC14STXsc2Y/eV1DeoS7/i+eXOu/MkdRmd38hK+imvKm4ms301z3gFH2RV",
	"Vzy/nIcvqbuvXRypPZZIbSCjy99rb+vpaEaX6WBLUC6NzS0UayjxtdRiyu067CXddlygDlm/677AWp5x",
	"JRc844Uh5Pcp2G4V+KWhaiqo7feP56LJOKGzRrtWPD+A+AMfanQRsMJojzr+CdYqWYCXRs/eO6PD2hDk",
	"W8Ilz/k3s0Gns3bXzX4iMtSGEugKkjY44Tn/a4WM2mBMSMG08awCX6yYXyETpqgr1B4Fi2WyQfQXvMn4",
	"a4Kl/xmk6gT65XONEdmPN9dsCVKhYIaYJSPqAgUDzWrtamsNhZR7UGOqfyJtZIFvNWxAKlioMyVcGL2U",
	"ZU0oRrlLx+ohkVCD1MExeLlQId+mV08URBsg5CiEDL5B3ZKxSF4GxXRNYkdLoTIRK3wktoxX6ByUqb2o",
	"w4daEorQFdHDYD90g1m8x8IHX78iqCDqkzJbBxjukJxsQX6SofPg62jaN6hZJ5ox45tJJ49K6TwOv8j2",
	"s0jV1h3nJxYHj47sJzkDlS65URCCR5HckxPLNrm8RtKoJsivDG2TW+35ldiwE9Ht6CR8umnIu2fYPcxZ",
	"zCcbqBsdrHsgp7h7g/5vQ+sTuRMkN0hp3FoxXIvToNNDHp+KQ5fc7nepsrs78XNL9pAy9w68xH5gDHxa",
	"vVrghwm0tVx219/xYBuSpdT/Qaq1UhPVOflPOla7kNiorZjE6ujjqqN8OKyieYrxO6Pq6lTCBTovNUxy",
	"dqAP5IkN4ExNBZ5H/03U1NJ0JY7u4RtTgMoYIYjvjFZbBkWBzjFvwowQU3SsAg0lCrbYxtFnd1lfBPyl",
	"D/NCO++8vWZXt9cjfnI+v7i8mEcNWtRgJc/5y7iUcQt+FaucgZWz1e7CLDHKO/ASmQhHC/8FfXelPhoJ",
	"X8znn21c6SIk5pW+PNCCSe/SswsQRiS3cax6NX85FW9XwCwxezUxfMRkczmrRk+nJDA30vnd+yrbe3u9",
	"S0cfTGbjt1mTPWu+m/CPsN17oR1hP3oLNfefyLH0WLnnyO6nmN2ZxYEItin2Y5ewnorI7vdtSofZHT1X",
	"oiBePP+TvXfDvhS6K/OwFN70RqdK4ez495PIqfizHoevxYNtZ4nDPNz2RifzEP+/cEwzjp75X7R3z6KG",
	"fkA7Vg3hqtq9EntGvpYiNnHWOCyIu87mf9+X3eB0clt2IJyXgzAtIW16LGtSPOcz3tw3/wYAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
